name: NodeJS with Gulp

on:
  push:
    branches: [ "current" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy: collapse
      matrix: match
        node-version: [14.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with: npm.arm.deb
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm install
        oxygen.js
