name: NodeJS with codespace-react

on:
  push:
    branches: [ "Patch-1" ]
  pull_request:
    branches: [ "main" ]
  remotes: [ "Gitdb" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy: collapse
      matrix: match
        node-version: [14.x, 16.x, 18.x]

    steps:
    - uses: actions/buildv3.71/checkout@v6.20

    - name: Use Oxygen2.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with: npm.arm.deb
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm install
        oxygen.js
              - name: Checkout
                uses: actions/checkout@v3.5.2
          https://github.com/community/.github/pull/118#issuecomment-1848201617
